title: ''
baseURL: 'https://kmax2001.github.io/'

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true

enableGitInfo: false
summaryLength: 30
enableEmoji: true
enableRobotsTXT: true

pagination:
  pagerSize: 10

outputs:
  home:
    - HTML
    - RSS
    - headers
    - redirects
    - backlinks
  section:
    - HTML
    - RSS

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture

timeout: 600000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  _merge: deep
  goldmark:
    renderer:
      unsafe: true

security:
  _merge: deep

sitemap:
  _merge: deep